spring:
  application:
    name: master-thesis-app
  cloud:
    config:
      discovery:
        enabled: true
  zipkin:
    baseUrl: http://zipkin-server:9411/
  sleuth:
    sampler:
      probability: 1.0
  ssl:
    bundle:
      jks:
        main:
          keystore:
            location: "/master-thesis-faron.pl-keystore.p12"
            password: ${MASTER_THESIS_CERT_PASSWORD}
            type: "PKCS12"
          truststore:
            location: "/master-thesis-faron.pl-truststore.p12"
            password: ${MASTER_THESIS_CERT_PASSWORD}
            type: "PKCS12"
        server:
          keystore:
            location: "/master-thesis-faron.pl.p12"
            password: ${MASTER_THESIS_CERT_PASSWORD}
            type: "PKCS12"
          truststore:
            location: "/master-thesis-faron.pl-truststore.p12"
            password: ${MASTER_THESIS_CERT_PASSWORD}
            type: "PKCS12"

server:
  ssl:
    enabled: true
    enabled-protocols: [ TLSv1.2 ]
    client-auth: want
    bundle: server

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  key: ${MASTERTHESIS_JWT_KEY}
  access-token-expiration-time: 900000
  refresh-token-expiration-time: 3600000
  cookie-max-age: 3600
  issuer: master-thesis-faron

performance:
  url: ${NEXT-INSTANCE-URL}
  next: ${HAS-NEXT-INSTANCE}